name: Got Triggered

on:
  repository_dispatch:
    types: [run-external-workflow]
  workflow_dispatch: 
  
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in Repo B
        run: |
          echo "Hello World"
